export default {
  SUPABASE_URL: "SUPABASE_URL_VALUE",
  SUPABASE_ANON_KEY: "SUPABASE_ANON_KEY_VALUE",
  JWT_SECRET: "JWT_SECRET_VALUE",
  CRYPTO_SECRET: "CRYPTO_SECRET_VALUE",
  NODEMAILER_EMAIL: "NODEMAILER_EMAIL_VALUE",
  NODEMAILER_PW: "NODEMAILER_PW_VALUE",
};
